// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jdezscreenshotservice.Models;

namespace jdezscreenshotservice.Migrations
{
    [DbContext(typeof(jdezscreenshotserviceContext))]
    [Migration("20181122142852_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("jdezscreenshotservice.Models.ScreenshotItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Episode");

                    b.Property<string>("Height");

                    b.Property<string>("Series");

                    b.Property<string>("Subtitle");

                    b.Property<string>("Timestamp");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("ScreenshotItem");
                });
#pragma warning restore 612, 618
        }
    }
}
